---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: application
        image: <image url> #add the url
        envFrom:
        - secretRef:
            name: application-secret
        ports:
        - containerPort: 9101
---
apiVersion: v1
kind: Service
metadata:
  name: application
  namespace: default
spec:
  selector:
    app: application
  ports:
    - protocol: TCP
      port: 9101
      targetPort: 9101
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: application-secret
  namespace: default
type: Opaque
data:
  API_ENDPOINT: <>
  API_TOKEN: <>
---

