apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "application.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "application.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.url }}
        envFrom:
        - secretRef:
            name: {{ template "application.fullname" . }}-secret
        ports:
        - containerPort: {{ .Values.ports.containerPort }}


