apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  API_ENDPOINT: {{ .Values.secret.API_ENDPOINT | b64enc | quote }}
  API_TOKEN: {{ .Values.secret.API_TOKEN | b64enc | quote }}

