apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ template "application.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.ports.servicePort }}
      targetPort: {{ .Values.ports.containerPort }}
  type: ClusterIP

